### ISSUE TITLE
About section leads to 404

### ISSUE THREAD

**Issue by azihassan** [chermehdi/chermehdi-blog#3]
Hi, just in case you didn't know, the "about" link displays a "page not found" error :

![image](https://user-images.githubusercontent.com/1638227/90917130-2d439180-e3da-11ea-8a1e-0e4cdcdb0193.png)

Nice blog btw, I enjoyed your Rust article :+1:

**Comment by chermehdi** [comment]
Thanks for opening this, And I am glad that you enjoyed the article, more coming soon (hopefully).

I will keep this open until I fix it.
